### ISSUE TITLE
Question regarding scss stylings and leveraging the shadow root.

### ISSUE THREAD

**Issue by Slavrix** [mjwheatley/ionic2-meteor-boilerplate#2]
Currently the project is set to have all the styling added to the theme folder which is situated outside the app and is separate to the components and pages.

The build process then merges them all into one file, instead of us loading separate styles per component and using the shadow root.

Is there a way we are able to build it with loading the style per component as we would when building an angular2 or ionic2 app ?

if we wrap the scss for each seperate page/component in {}

eg
```
home-page {
//classes for home page go here
}
```

will that do it for us ?

~edit

Yes it works very well if we do it this way.

Each scss file added to the theme/pages/<pagename> folders should be wrapped with the pages selector and {}

To ensure that the scss that you write targets only that component/page

If you want them to be golbal then the app.variables.scss and the app.core.scss are the places to put it.

**Comment by mjwheatley** [comment]
Yes that is correct.  Sorry that was not more clear from the README.  I tried to indicate that you could add component specific scss by including an import statement to the app.core.scss but I failed to mention the structure of the component scss file.  Thank you for clarifying.  I will edit the README to include an example.
