### ISSUE TITLE
where to put ionic supporting files

### ISSUE THREAD

**Issue by Slavrix** [mjwheatley/ionic2-meteor-boilerplate#3]
Where do we add files such as the config.xml (if its needed at all)
If it isn't then where do we manage splashscreen/icons locations from for the building off the apk/ipa ?

Also, files such as the ionic.config.json  for using ionic cloud, where should they go?

**Comment by mjwheatley** [comment]
Most of what would be in the config.xml would go in `app/mobile-config.js`.  I have commented out example code for splashscreen and icons.

I'm not familiar with using ionic cloud.  If I may ask, what features would it provide?  Also why would you need it in conjunction with a Meteor server?

**Comment by mjwheatley** [comment]
For ionic cloud setup https://docs.ionic.io/setup.html I would palace your app ID in `config/development/settings` under `private.ionicCloud.appId` (or however you want to name/structure it) and use `Meteor.settings.private.ionicCloud.appId` to use the value in `app.module.ts`

**Comment by Slavrix** [comment]
Awsome
Yea i just found the mobile-config.js stuff and have now implemented that (had some issues with some packages because im building on a windows machine currently (https://github.com/meteor/meteor/issues/7358)

but i have that wokring now, 
Ill give that a go with the ionic cloud configs
